### ISSUE TITLE
candle.h is not present in engine directory

### ISSUE THREAD

**Issue by tfarina** [jnaulet/cresus#1]
But it is included in many indicator files.

**Comment by jnaulet** [comment]
Indicators that have been commented out in the CMakeLists.txt file have not been ported from the old API to the new one & i don't plan on doing this any time soon. It's not an awfully big job, tell me which indicator interests you & i show you how the port can be made

**Comment by tfarina** [comment]
Okay. I was interested in the rsi indicator.

**Comment by jnaulet** [comment]
Port is done as one single commit to show how to port from old to new API

**Comment by tfarina** [comment]
Thank you.
